window.facts = [
"Did you know honey never spoils?",
"Did you know a day on Venus is longer than a year on Venus?",
"Did you know octopuses have three hearts?",
"Did you know bananas are berries but strawberries aren’t?",
"Did you know your brain is sometimes more active when you sleep?",
"Did you know dolphins call each other by name?",
"Did you know chess has more possible moves than atoms in the universe?",
"Did you know sea otters hold hands when they sleep?",
"Did you know spiders can’t fly but they can ride the wind?",
"Did you know the Eiffel Tower grows in summer?",
"Did you know turtles can breathe through their butts?",
"Did you know fingerprints aren’t just on fingers but also on toes?",
"Did you know cows have best friends?",
"Did you know Sloths can hold their breath longer than dolphins?",
"Did you know hot water freezes faster than cold water?",
"Did you know the heart can beat outside the body?",
"Did you know blueberries can’t be blue on the inside?",
"Did you know sharks are older than trees?",
"Did you know some metals explode if they touch water?",
"Did you know butterflies taste with their feet?",
"Did you know most of the internet is underwater?",
"Did you know the moon has moonquakes?",
"Did you know cats can’t taste sweetness?",
"Did you know astronauts grow taller in space?",
"Did you know the human nose can detect over a trillion smells?",
"Did you know tomatoes have more genes than humans?",
"Did you know there’s a planet made of diamonds?",
"Did you know jellyfish can clone themselves?",
"Did you know lightning is hotter than the sun?",
"Did you know snakes smell with their tongues?",
"Did you know some frogs can freeze without dying?",
"Did you know peanuts aren’t actually nuts?",
"Did you know bees can recognize human faces?",
"Did you know a group of flamingos is called a flamboyance?",
"Did you know the first oranges weren’t orange?",
"Did you know wombat poop is shaped like cubes?",
"Did you know there’s a fish that can climb trees?",
"Did you know rats laugh when tickled?",
"Did you know clouds can weigh millions of pounds?",
"Did you know an octopus can taste through its arms?",
"Did you know camels have three eyelids?",
"Did you know a shrimp’s heart is in its head?",
"Did you know the ocean has lost 90% of its big fish?",
"Did you know avocados are poisonous to birds?",
"Did you know Antarctica has no reptiles or snakes?",
"Did you know Pluto has blue skies?",
"Did you know koalas have fingerprints like humans?",
"Did you know some turtles breathe through their shells?",
"Did you know trees talk to each other underground?",
"Did you know bubble wrap was originally wallpaper?",
"Did you know your ears never stop growing?",
"Did you know cows can climb stairs but not go down them?",
"Did you know the longest English word has 189,819 letters?",
"Did you know pangolins are the most trafficked animal in the world?",
"Did you know Saturn could float in water?",
"Did you know the sun makes up 99% of our solar system?",
"Did you know dragonflies can fly backward?",
"Did you know mosquitoes are the deadliest animals on Earth?",
"Did you know baby carrots are just shaved big carrots?",
"Did you know fish can drown in water?",
"Did you know a snail can sleep for 3 years?",
"Did you know some ants explode to protect their colony?",
"Did you know the human eye can see 7 million colors?",
"Did you know cheetahs can’t roar?",
"Did you know crocodiles can’t stick out their tongue?",
"Did you know potatoes can grow in space?",
"Did you know the world’s largest desert is Antarctica?",
"Did you know there’s a jellyfish that’s basically immortal?",
"Did you know humans share 60% of DNA with bananas?",
"Did you know sharks don’t get cancer as often as us?",
"Did you know stars can sing?",
"Did you know fire needs gravity to burn correctly?",
"Did you know bees can fly higher than Mount Everest?",
"Did you know spiders recycle their webs by eating them?",
"Did you know some mushrooms can glow in the dark?",
"Did you know Google was almost called BackRub?",
"Did you know elephants think humans are cute?",
"Did you know ice cream used to be salty?",
"Did you know tomatoes were once considered poisonous?",
"Did you know the shortest war in history was 38 minutes?",
"Did you know polar bears have black skin?",
"Did you know cows produce more milk when they listen to music?",
"Did you know the first 3D movie was made in 1922?",
"Did you know there’s a basketball court on top of the Supreme Court?",
"Did you know humans are the only animals that blush?",
"Did you know horses can’t throw up?",
"Did you know Mount Everest grows every year?",
"Did you know your taste buds have a lifespan of 10 days?",
"Did you know seeds can survive in space?",
"Did you know birds don’t pee?",
"Did you know dogs can smell your feelings?",
"Did you know your stomach gets a new lining every few days?",
"Did you know gold has been found in every continent?",
"Did you know rabbits can die from loneliness?",
"Did you know Saturn has more than 140 moons?",
"Did you know TikTok used to be called Musical.ly?",
"Did you know the universe is still making stars right now?",
"Did you know humans glow in the dark but we can’t see it?",
"Did you know the biggest frog is bigger than a newborn baby?",
"Did you know Earth once had two moons?",
"Did you know red is the first color a baby sees?",
"Did you know hot water can freeze faster than cold water?",
"Did you know cockroaches can live for weeks without heads?",
"Did you know flamingos are born gray, not pink?",
"Did you know honeybees can recognize human faces?",
"Did you know sloths can hold their breath longer than dolphins?",
"Did you know butterflies can see ultraviolet light?",
"Did you know some turtles can breathe through their skin?",
"Did you know cheetahs can’t roar?",
"Did you know pandas spend up to 14 hours a day eating?",
"Did you know frogs drink water through their skin?",
"Did you know jellyfish don’t have brains?",
"Did you know ants never sleep?",
"Did you know spiders can’t fly but can travel with the wind?",
"Did you know penguins propose with a pebble?",
"Did you know crocodiles can’t stick out their tongues?",
"Did you know dragonflies can fly in every direction?",
"Did you know a snail can sleep for three years?",
"Did you know giraffes only need 30 minutes of sleep per day?",
"Did you know mosquitoes are the deadliest animals on Earth?",
"Did you know bats always turn left when leaving a cave?",
"Did you know kangaroos can’t walk backward?",
"Did you know a group of owls is called a parliament?",
"Did you know wombats have cube-shaped poop?",
"Did you know goats have accents?",
"Did you know parrots can live over 80 years?",
"Did you know sharks don’t get cavities?",
"Did you know horses can’t vomit?",
"Did you know cats have over 20 muscles in each ear?",
"Did you know cows have best friends?",
"Did you know lobsters taste with their legs?",
"Did you know rhinos are related to horses?",
"Did you know chickens can remember over 100 faces?",
"Did you know octopuses have nine brains?",
"Did you know dolphins sleep with one eye open?",
"Did you know elephants can smell water miles away?",
"Did you know hedgehogs can swim?",
"Did you know corgis were bred to herd cattle?",
"Did you know ducks have waterproof feathers?",
"Did you know bees can make colored honey?",
"Did you know reindeer eyes change color in winter?",
"Did you know some fish can glow in the dark?",
"Did you know sea stars can regrow arms?",
"Did you know shrimp can snap their claws louder than a gunshot?",
"Did you know otters hold hands while sleeping?",
"Did you know rabbits can see behind them without turning?",
"Did you know pigeons can do math?",
"Did you know zebras are black with white stripes?",
"Did you know snakes can sense earthquakes?",
"Did you know toucans toss food into the air to eat it?",
"Did you know bees can understand the concept of zero?",
"Did you know pigs are smarter than dogs?",
"Did you know butterflies taste with their feet?",
"Did you know camels have three eyelids?",
"Did you know flamingos bend their legs at the ankle, not the knee?",
"Did you know turtles can live longer than humans?",
"Did you know wolves have over 200 million scent cells?",
"Did you know blue whales are louder than jet engines?",
"Did you know alpacas hum when they are curious?",
"Did you know ants can lift 50 times their body weight?",
"Did you know panda babies are born blind and tiny like sticks of butter?",
"Did you know starfish have no blood?",
"Did you know sharks existed before trees?",
"Did you know bats are the only mammals that can fly?",
"Did you know hummingbirds can fly backward?",
"Did you know crabs communicate by waving their claws?",
"Did you know butterflies cannot fly if they are too cold?",
"Did you know snails have thousands of teeth?",
"Did you know killer whales are actually dolphins?",
"Did you know cats can jump six times their height?",
"Did you know bees can fly higher than Mount Everest?",
"Did you know bears can run faster than horses?",
"Did you know clownfish change gender?",
"Did you know whales can communicate hundreds of miles apart?",
"Did you know ants farm and herd other insects?",
"Did you know kangaroos can’t move their legs separately on land?",
"Did you know foxes have whiskers on their legs?",
"Did you know sharks can smell a drop of blood in the ocean?",
"Did you know frogs absorb water through their skin instead of drinking?",
"Did you know parrots name their babies?",
"Did you know jellyfish have survived 500 million years?",
"Did you know some birds can sleep while flying?",
"Did you know seahorses are the only animals where males give birth?",
"Did you know bees can recognize different human voices?",
"Did you know dolphins can help humans in danger?",
"Did you know giraffes have the same number of neck bones as humans?",
"Did you know sharks don’t have bones?",
"Did you know some lizards can squirt blood from their eyes?",
"Did you know elephants can run quietly?",
"Did you know horses can’t breathe through their mouths?",
"Did you know bees sometimes sting other bees?",
"Did you know sheep can’t right themselves if they fall on their backs?",
"Did you know dragonflies have nearly 360-degree vision?",
"Did you know rabbits’ teeth never stop growing?",
"Did you know cows moo in accents based on where they live?",
"Did you know armadillos can float in water?",
"Did you know pig hearts can beat inside a human body during surgery?",
"Did you know frogs can see in color in the dark?",
"Did you know dolphins can sleep with half their brain at a time?",
"Did you know cats can heal themselves with purring?",
"Did you know rats laugh when tickled?",
"Did you know whales can get sunburned?",
"Did you know the Eiffel Tower can grow taller in the summer?",
"Did you know the Great Wall of China isn’t visible from space with the naked eye?",
"Did you know Mount Everest grows a few millimeters every year?",
"Did you know a day on Venus is longer than a year on Venus?",
"Did you know the Amazon rainforest produces 20% of Earth’s oxygen?",
"Did you know lightning strikes Earth about 100 times every second?",
"Did you know Antarctica is the largest desert in the world?",
"Did you know some sand dunes can sing?",
"Did you know volcanoes can create new islands?",
"Did you know Earth once had two moons?",
"Did you know the Dead Sea is so salty you can float without effort?",
"Did you know there are underwater volcanoes larger than any on land?",
"Did you know the Sahara Desert was once a rainforest?",
"Did you know the Nile is the longest river on Earth?",
"Did you know clouds can weigh millions of pounds?",
"Did you know Hawaii moves 3 inches closer to Japan every year?",
"Did you know plants can communicate using chemicals?",
"Did you know trees can talk through underground fungi networks?",
"Did you know some lakes explode?",
"Did you know the North Pole moves every year?",
"Did you know Earth’s rotation is slowing down?",
"Did you know waterfalls can flow upward with strong winds?",
"Did you know spiders can make silk stronger than steel?",
"Did you know worms have five hearts?",
"Did you know honey never spoils?",
"Did you know peanuts aren’t nuts?",
"Did you know bananas are berries but strawberries aren’t?",
"Did you know tomatoes were once considered poisonous?",
"Did you know carrots were originally purple?",
"Did you know celery is mostly water?",
"Did you know chocolate was once used as money?",
"Did you know popcorn is one of the oldest snacks on Earth?",
"Did you know lemon floats but lime sinks?",
"Did you know apples float because they’re 25% air?",
"Did you know rice has over 40,000 varieties?",
"Did you know Coca-Cola was originally green?",
"Did you know potatoes were grown in space?",
"Did you know peanuts can be used to make dynamite?",
"Did you know beeswax can preserve food for years?",
"Did you know ketchup was once sold as medicine?",
"Did you know cheese is one of the oldest human foods?",
"Did you know pineapples take up to 2 years to grow?",
"Did you know spinach gives you a tiny iron boost — not super strength?",
"Did you know pickles are just cucumbers that got a salty makeover?",
"Did you know the first oranges weren’t orange?",
"Did you know grapes explode in the microwave?",
"Did you know lettuce was sacred in ancient Egypt?",
"Did you know watermelon is 92% water?",
"Did you know mushrooms aren’t plants or animals — they’re fungi?",
"Did you know honeybees are essential for 1/3 of the food we eat?",
"Did you know astronauts can’t burp in space?",
"Did you know your bones are constantly being replaced?",
"Did you know thumbs have their own pulse?",
"Did you know sneezes can travel up to 100 mph?",
"Did you know fingerprints improve grip?",
"Did you know newborn babies don’t shed tears?",
"Did you know you can’t tickle yourself?",
"Did you know dreams are often only 5 minutes long?",
"Did you know yawning is contagious even for dogs?",
"Did you know your tongue is the fastest healing part of your body?",
"Did you know humans glow in the dark — but eyes can’t see it?",
"Did you know everyone has a unique smell?",
"Did you know your big toe carries the most weight when walking?",
"Did you know taste buds live for about 10 days?",
"Did you know your lungs could cover a tennis court if spread out?",
"Did you know your stomach gets a new lining every few days?",
"Did you know your nails grow faster in summer?",
"Did you know your body has enough iron for a small nail?",
"Did you know smiles are easier to make than frowns?",
"Did you know we are tallest in the morning?",
"Did you know your heart can beat outside your body?",
"Did you know your eyes blink in perfect sync?",
"Did you know goosebumps are a leftover survival instinct?",
"Did you know laughter burns calories?",
"Did you know chewing gum helps you focus?",
"Did you know sneezes stop your heart for a millisecond?",
"Did you know hair is stronger than copper wire?",
"Did you know your blood makes up about 8% of your weight?",
"Did you know blue eyes are more sensitive to light?",
"Did you know your liver can regrow itself?",
"Did you know your hearing never turns off — even when sleeping?",
"Did you know humans share 60% of DNA with bananas?",
"Did you know left-handed people blink more than right-handed people?",
"Did you know the brain runs on the same power as a light bulb?",
"Did you know sweating keeps your brain from overheating?",
"Did you know the average human farts 14 times a day?",
"Did you know your belly button is a habitat for bacteria?",
"Did you know you get shorter throughout the day?",
"Did you know cold weather makes nails grow slower?",
"Did you know wrinkles form faster if you sleep on your face?",
"Did you know your stomach acid can melt zinc?",
"Did you know earwax cleans your ears automatically?",
"Did you know fingerprints can recover after being burned?",
"Did you know your bones are 5 times stronger than steel?",
"Did you know humans forget 80% of their dreams?",
"Did you know your brain can store infinite memories?",
"Did you know everyone has a unique tongue print?",
"Did you know allergic reactions are your body being overprotective?",
"Did you know you can’t breathe and talk at the same time?",
"Did you know blinking keeps your brain from overheating?",
"Did you know taste buds decrease with age?",
"Did you know sunlight triggers happiness chemicals in your brain?",
"Did you know camels have three eyelids to protect against sand?",
"Did you know koalas sleep up to 22 hours a day?",
"Did you know baby kangaroos are the size of jelly beans?",
"Did you know flamingos are only pink because of their diet?",
"Did you know sloths can hold their breath longer than dolphins?",
"Did you know octopuses can taste with their arms?",
"Did you know crocodiles can climb trees?",
"Did you know bees never sleep?",
"Did you know pigs can’t look up into the sky?",
"Did you know turtles can live for more than 150 years?",
"Did you know some lizards can shoot blood from their eyes?",
"Did you know snakes can smell with their tongue?",
"Did you know frogs drink water through their skin?",
"Did you know cats can make 100 different sounds?",
"Did you know dogs’ nose prints are unique like fingerprints?",
"Did you know dolphins sleep with one eye open?",
"Did you know spiders can regrow lost legs?",
"Did you know elephants are the only mammals that can’t jump?",
"Did you know cows moo in regional accents?",
"Did you know ants don’t have lungs?",
"Did you know penguins give their mate a pebble as a gift?",
"Did you know giraffes only sleep about 30 minutes per day?",
"Did you know bats are the only mammals that can fly?",
"Did you know whales can talk to each other across oceans?",
"Did you know reindeer eyes change color in winter?",
"Did you know cheetahs can’t roar?",
"Did you know starfish can regrow their entire bodies?",
"Did you know kangaroos can’t walk backward?",
"Did you know hippos have pink sweat?",
"Did you know goldfish can learn tricks?",
"Did you know the pistol shrimp’s snap can create a bubble hotter than the sun?",
"Did you know ostriches can run faster than horses?",
"Did you know butterflies remember their lives as caterpillars?",
"Did you know seagulls can drink ocean water?",
"Did you know sharks don’t get bone disease because they have no bones?",
"Did you know goats can climb trees?",
"Did you know zebras’ stripes confuse predators?",
"Did you know rabbits can’t puke?",
"Did you know bees can recognize human faces?",
"Did you know kangaroos can swim?",
"Did you know jellyfish have existed for over 500 million years?",
"Did you know chickens can dream?",
"Did you know cats spend 70% of their life sleeping?",
"Did you know owls can rotate their heads almost all the way around?",
"Did you know flamingos stand on one leg to save body heat?",
"Did you know snakes can sunburn?",
"Did you know dolphins can tell each other jokes?",
"Did you know ants can lift 50 times their body weight?",
"Did you know birds are living dinosaurs?",
"Did you know sharks can smell a drop of blood from miles away?",
"Did you know raccoons wash their food before eating?",
"Did you know bees can solve math problems?",
"Did you know wolves have best friends?",
"Did you know cats can drink seawater?",
"Did you know some fish glow in the dark?",
"Did you know crabs can regrow their claws?",
"Did you know polar bears have black skin?",
"Did you know foxes purr like cats?",
"Did you know horses can sleep standing up?",
"Did you know turtles can live without food for months?",
"Did you know owls don’t have eyeballs — just eye tubes?",
"Did you know baby elephants suck their trunks like pacifiers?",
"Did you know whales can die if they stay underwater too long?",
"Did you know baby polar bears are the size of a potato?",
"Did you know bats can eat 1,200 mosquitoes per hour?",
"Did you know frogs don’t need to drink water?",
"Did you know chinchillas have the softest fur of any animal?",
"Did you know elephants hug with their trunks?",
"Did you know lizards can see in slow motion?",
"Did you know parrots can understand rhythm?",
"Did you know squirrels plant thousands of trees by accident?",
"Did you know a shrimp’s heart is in its head?",
"Did you know frogs absorb water through their feet?",
"Did you know dogs can predict storms?",
"Did you know camels store fat — not water — in their humps?",
"Did you know ants can survive underwater for 24 hours?",
"Did you know crocodiles can live over 100 years?",
"Did you know penguins have knees under their feathers?",
"Did you know elephants can die of heartbreak?",
"Did you know sharks can live for over 400 years?",
"Did you know horses can recognize emotions in human voices?",
"Did you know owls are silent flyers?",
"Did you know goats have accents?",
"Did you know bees dance to communicate?",
"Did you know giraffes have the same number of neck bones as humans?",
"Did you know crows can hold grudges?",
"Did you know parrots name their babies with unique calls?",
"Did you know dolphins help sick or injured friends?",
"Did you know kangaroos can’t fart?",
"Did you know rhinos have poor eyesight but great hearing?",
"Did you know squirrels can fall 100 feet without getting hurt?",
"Did you know bees flap their wings 230 times per second?",
"Did you know horses can’t vomit?",
"Did you know some worms can regrow their heads?",
"Did you know lions sleep up to 20 hours a day?",
"Did you know butterflies can see ultraviolet light?",
"Did you know penguins propose with rocks?",
"Did you know cats can jump six times their height?",
"Did you know goats can learn their name and come when called?",
"Did you know turtles can breathe through their butts?",
"Did you know rats laugh when tickled?",
"Did you know cows have best friends and get sad when separated?",
"Did you know octopuses can solve puzzles?",
"Did you know cats have whiskers on their legs?",
"Did you know dolphins give each other gifts like seaweed?",
"Did you know camels can drink 50 gallons of water in one go?",
"Did you know goldfish can remember things for months?",
"Did you know crocodiles can’t stick out their tongue?",
"Did you know goats have rectangular pupils for wider vision?",
"Did you know squirrels can find food buried under snow?",
"Did you know snakes only eat animals — never plants?",
"Did you know flamingos bend their ankles — not their knees?",
"Did you know sea otters hold hands when they sleep?",
"Did you know elephants can hear storms 150 miles away?",
"Did you know sharks are older than trees?",
"Did you know reindeer hooves change for winter traction?",
"Did you know sloths are excellent swimmers?",
"Did you know frogs can see in all directions at once?",
"Did you know pigs dream just like humans?",
"Did you know wolf howls are like fingerprints — all unique?",
"Did you know cats can run faster than most Olympians?",
"Did you know bees have five eyes?",
"Did you know butterflies drink tears from other animals?",
"Did you know turtles cry to clean their eyes in saltwater?",
"Did you know dolphins have two stomachs?",
"Did you know owls can’t move their eyes — so they move their heads?",
"Did you know a giraffe’s kick can kill a lion?",
"Did you know ants take naps throughout the day?",
"Did you know bats have super strong immune systems?",
"Did you know crocodiles swallow stones to dive deeper?",
"Did you know horses grow mustaches sometimes?",
"Did you know cats can survive falling from skyscrapers?",
"Did you know whales sing louder than a jet engine?",
"Did you know dogs can smell your feelings?",
"Did you know rabbits can see behind themselves without turning?",
"Did you know rhinos communicate with poop?",
"Did you know sea lions can walk on land using their back flippers?",
"Did you know bees sometimes sting other bees?",
"Did you know camels can close their nostrils during sandstorms?",
"Did you know dolphins can recognize themselves in mirrors?",
"Did you know kangaroos use their tails like a third leg?",
"Did you know fish can drown without oxygen?",
"Did you know elephants can remember 30+ years of locations?",
"Did you know seahorses are the only animals where males give birth?",
"Did you know hippos can’t swim — they walk underwater?",
"Did you know sharks have built-in GPS using Earth’s magnetic field?",
"Did you know parrots can live longer than humans?",
"Did you know jellyfish are immortal… kinda?",
"Did you know cats sweat through their paws?",
"Did you know owls have special feathers that silence their flight?",
"Did you know goats wag their tails when happy?",
"Did you know dolphins have lifelong friendships?",
"Did you know sea turtles navigate using the Earth’s magnetic field?",
"Did you know foxes can jump straight up to catch prey?",
"Did you know cheetahs can go from 0 to 60 mph in 3 seconds?",
"Did you know zebras can’t sleep alone?",
"Did you know jellyfish have no brain or heart?",
"Did you know some ants farm fungi like tiny gardeners?",
"Did you know hummingbirds can fly backward?",
"Did you know sharks don’t blink — a lid slides over their eyes?",
"Did you know sloths only poop once a week?",
"Did you know cats have a secret second eyelid?",
"Did you know whales don’t drink seawater — they get water from food?",
"Did you know starfish wear their bones on the outside?",
"Did you know wolves communicate with facial expressions?",
"Did you know squirrels pretend to bury food to trick thieves?",
"Did you know dolphins use tools just like humans?",
"Did you know cows face north or south when eating?",
"Did you know ants have two stomachs?",
"Did you know butterflies can smell using their antennae?",
"Did you know frogs can freeze solid and still survive?",
"Did you know elephants can swim many miles without rest?",
"Did you know crocodiles can go a year without eating?",
"Did you know pigs can get sunburnt?",
"Did you know cats purr to heal themselves?",
"Did you know bees can make colored honey from candy?",
"Did you know birds know when an egg was swapped by humans?",
"Did you know dolphins have names for each other?",
"Did you know sharks replace each lost tooth in days?",
"Did you know owls have tube-shaped eyes for sharp long-distance vision?",
"Did you know some turtles can live over 200 years?",
"Did you know butterflies taste with their feet?",
"Did you know ants don’t sleep?",
"Did you know flamingos are born gray, not pink?",
"Did you know otters hold hands while sleeping so they don’t drift apart?",
"Did you know cows have best friends and get stressed when separated?",
"Did you know the shortest war in history lasted about 38 minutes?",
"Did you know a sneeze travels about 100 miles per hour?",
"Did you know bananas glow blue under blacklight?",
"Did you know bees can recognize human faces?",
"Did you know your brain is sometimes more active while you sleep?",
"Did you know turtles can breathe through their butts?",
"Did you know octopuses have three hearts?",
"Did you know Scotland has 421 words for ‘snow’?",
"Did you know the moon has moonquakes?",
"Did you know your stomach gets a new lining every few days?",
"Did you know dolphins call each other by name?",
"Did you know polar bear skin is actually black?",
"Did you know pigs can’t look straight up into the sky?",
"Did you know elephants are the only animals that can’t jump?",
"Did you know goldfish can remember things for months, not seconds?",
"Did you know sloths can hold their breath longer than dolphins?",
"Did you know frogs can freeze and still survive?",
"Did you know the Eiffel Tower grows in summer from heat?",
"Did you know honey never spoils?",
"Did you know humans share 50% of their DNA with bananas?",
"Did you know the longest hiccup lasted 68 years?",
"Did you know sea otters have a favorite rock to break shells?",
"Did you know butterflies can see ultraviolet light?",
"Did you know wombat poop is cube-shaped?",
"Did you know turtles can live for over 150 years?",
"Did you know sharks existed before trees?",
"Did you know peanuts aren’t actually nuts?",
"Did you know a day on Venus is longer than a year on Venus?",
"Did you know snails have thousands of teeth?",
"Did you know cats can’t taste sweetness?",
"Did you know oranges were originally green?",
"Did you know crocodiles can climb trees?",
"Did you know jellyfish have existed for over 600 million years?",
"Did you know koalas sleep up to 22 hours a day?",
"Did you know a group of crows is called a murder?",
"Did you know parrots can live for over 80 years?",
"Did you know the heart of a blue whale is as big as a small car?",
"Did you know dragonflies can fly up to 60 mph?",
"Did you know some metal can explode if it touches water?",
"Did you know spiders can rebuild their webs every day?",
"Did you know giraffes have the same number of neck bones as humans?",
"Did you know swans can be left- or right-winged?",
"Did you know hippos sweat a red sunscreen?",
"Did you know astronauts grow taller in space?",
"Did you know your feet make up 25% of the bones in your body?",
"Did you know fire can’t burn in space the same way it does on Earth?",
"Did you know starfish can regenerate arms?",
"Did you know the unicorn is the national animal of Scotland?",
"Did you know kangaroos can’t walk backwards?",
"Did you know your bones are stronger than steel?",
"Did you know lightning can strike the same place twice?",
"Did you know whales can communicate hundreds of miles?",
"Did you know raindrops aren’t tear-shaped but round?",
"Did you know cats have over 20 muscles in each ear?",
"Did you know some lizards can shoot blood from their eyes?",
"Did you know a single cloud can weigh over a million pounds?",
"Did you know there are more stars in the universe than grains of sand on Earth?",
"Did you know mosquitoes are the deadliest animals on Earth?",
"Did you know lobsters taste with their legs?",
"Did you know sharks don’t get cavities?",
"Did you know kangaroos can’t fart?",
"Did you know honeybees can flap their wings about 200 times per second?",
"Did you know a blue whale’s tongue can weigh as much as an elephant?",
"Did you know your hair is as strong as a wire of steel?",
"Did you know crocodiles can live over 100 years?",
"Did you know potatoes were the first food grown in space?",
"Did you know ants can lift 50 times their own weight?",
"Did you know some turtles can breathe through their shells?",
"Did you know flamingos get their pink color from food?",
"Did you know Saturn could float in water?",
"Did you know sharks don’t have bones?",
"Did you know hummingbirds can fly backward?",
"Did you know snow can be different colors, including pink?",
"Did you know strawberries aren’t actually berries?",
"Did you know blueberries are one of the only true blue foods?",
"Did you know penguins propose with pebbles?",
"Did you know goats have rectangular pupils?",
"Did you know bananas are berries?",
"Did you know there are fish that can walk on land?",
"Did you know humans glow in the dark but it’s too faint to see?",
"Did you know spiders can dream?",
"Did you know a group of flamingos is called a flamboyance?",
"Did you know snails can sleep for years?",
"Did you know octopuses can taste with their arms?",
"Did you know the human tooth is the only part of the body that can’t heal itself?",
"Did you know rabbits can’t vomit?",
"Did you know bees sometimes sting other bees?",
"Did you know the loudest animal on Earth is a tiny shrimp?",
"Did you know corals are actually animals, not plants?",
"Did you know wolves have best friends?",
"Did you know butterflies remember being caterpillars?",
"Did you know some frogs can glow under UV light?",
"Did you know cats can jump six times their height?",
"Did you know camels have three eyelids?",
"Did you know sharks can detect a heartbeat from miles away?",
"Did you know parrots can dance to music?",
"Did you know ants don’t have lungs?",
"Did you know your taste buds have a lifespan of about 10 days?",
"Did you know dolphins sleep with one eye open?",
"Did you know your brain stops recognizing the smell of your house?",
"Did you know butterflies can’t fly if they’re cold?",
"Did you know seahorses are the only animals where males give birth?",
"Did you know cats have whiskers on their legs?",
"Did you know earthworms have five hearts?",
"Did you know hummingbirds’ hearts can beat over 1,200 times per minute?",
"Did you know bees can get tired and humans sometimes give them sugar water?",
"Did you know hippos can’t swim — they walk underwater?",
"Did you know spiders reuse their webs by eating them?",
"Did you know crocodiles cry when they eat?",
"Did you know horses can sleep standing up?",
"Did you know your hair grows faster in warm weather?",
"Did you know you can’t hum while holding your nose?",
"Did you know frogs drink water through their skin?",
"Did you know the average person spends a year of their life looking for lost items?",
"Did you know the human eye can distinguish about 10 million colors?",
"Did you know ants can survive underwater for 24 hours?",
"Did you know birds don’t pee?",
"Did you know jellyfish don’t have brains?",
"Did you know most people can’t lick their elbow?",
"Did you know squirrels forget where they bury most of their nuts?",
"Did you know polar bears can smell food up to 20 miles away?",
"Did you know the tongue is the only muscle attached at just one end?",
"Did you know the heart can continue beating even outside the body?",
"Did you know spiders liquidize their food before eating it?",
"Did you know your fingernails grow faster than your toenails?",
"Did you know dogs can understand up to 250 words?",
"Did you know horses can’t breathe through their mouths?",
"Did you know some fish don’t sleep?",
"Did you know flamingos can only eat with their heads upside down?",
"Did you know some snails have hairy shells?",
"Did you know your brain is 75% water?",
"Did you know dolphins give gifts to impress each other?",
"Did you know sharks have been around longer than Saturn’s rings?",
"Did you know birds are dinosaurs?",
"Did you know sea lions clap underwater?",
"Did you know a whale’s heartbeat can be heard two miles away?",
"Did you know dogs’ noses are as unique as fingerprints?",
"Did you know cows can walk up stairs but not down them?",
"Did you know cats can rotate their ears 180 degrees?",
"Did you know tomatoes were once feared as poisonous?",
"Did you know honeybees can recognize royalty in pictures?",
"Did you know lizards can detach their tails to escape?",
"Did you know reindeer eyes turn blue in winter?",
"Did you know sharks sleep with their eyes open?",
"Did you know trees can talk to each other using underground fungi?",
"Did you know baby rabbits are called kittens?",
"Did you know laughter burns calories?",
"Did you know ducks have accents?",
"Did you know ants have two stomachs?",
"Did you know bats are the only flying mammals?",
"Did you know koalas have fingerprints almost identical to humans?",
"Did you know crocodiles can live for months without eating?",
"Did you know fish can drown in water?",
"Did you know your nails grow faster on your dominant hand?",
"Did you know pigs can’t sweat?",
"Did you know squirrels can fall from high places and survive?",
"Did you know giraffes only sleep about 30 minutes a day?",
"Did you know goats have amazing balance and can climb trees?",
"Did you know bees can’t see the color red?",
"Did you know spiders have blue blood?",
"Did you know bald eagles aren’t actually bald?",
"Did you know elephants can die of broken hearts?",
"Did you know butterflies need to drink from mud puddles for minerals?",
"Did you know cheetahs can’t roar?",
"Did you know rats laugh when tickled?",
"Did you know the average cloud can weigh over 1 billion pounds?",
"Did you know humans shed 600,000 skin particles each hour?",
"Did you know the smallest bone in your body is in your ear?",
"Did you know fireflies talk with light?",
"Did you know snakes smell with their tongues?",
"Did you know some turtles can live without food for over a year?",
"Did you know every snowflake has a different pattern?",
"Did you know ants leave scent trails to guide other ants?",
"Did you know parrots can solve puzzles better than toddlers?",
"Did you know humans are the only mammals that cry emotional tears?",
"Did you know worms can regrow parts of their bodies?",
"Did you know monkeys can understand money?",
"Did you know penguins have knees?",
"Did you know your belly button is a habitat for thousands of bacteria?",
"Did you know some birds sleep while flying?",
"Did you know slugs have four noses?",
"Did you know chickens can remember over 100 faces?",
"Did you know dogs’ ears have over a dozen muscles?",
"Did you know your bones are constantly being replaced?",
"Did you know fish can change their gender?",
"Did you know cats dream about hunting?",
"Did you know humans are taller in the morning?",
"Did you know shrimp can see colors humans can’t?",
"Did you know grasshoppers have ears on their bellies?",
"Did you know bees can fly higher than Mount Everest?",
"Did you know cows can smell things miles away?",
"Did you know sea turtles use Earth’s magnetic field to navigate?",
"Did you know giraffes don’t have vocal cords?",
"Did you know owls can spin their heads almost all the way around?",
"Did you know ducks can sleep with one eye open?",
"Did you know dolphins can see with sound?",
"Did you know stars twinkle because of Earth’s atmosphere?",
"Did you know ants stretch when they wake up?",
"Did you know the Eiffel Tower grows taller in summer because metal expands in heat?",
"Did you know time passes faster on the top floor of a building than on the bottom?",
"Did you know the internet weighs about the same as a strawberry?",
"Did you know glass can take millions of years to fully decompose?",
"Did you know astronauts’ suits cost around $12 million each?",
"Did you know outer space has a temperature of about -270°C?",
"Did you know the Great Wall of China isn’t visible from space with the naked eye?",
"Did you know the Earth is spinning at over 1,000 miles per hour?",
"Did you know some metals are so reactive they explode on contact with water?",
"Did you know the fastest thing in the universe is light?",
"Did you know clouds can move faster than 100 mph?",
"Did you know your phone is thousands of times more powerful than Apollo computers?",
"Did you know Saturn’s rings are mostly ice and rock?",
"Did you know you can’t burp in space?",
"Did you know a day on Venus is longer than a year on Venus?",
"Did you know the coldest place ever recorded is in Antarctica at -128°F?",
"Did you know a bolt of lightning is five times hotter than the Sun?",
"Did you know the Leaning Tower of Pisa was never perfectly straight?",
"Did you know the Moon is slowly drifting away from Earth?",
"Did you know Pluto has mountains made of ice?",
"Did you know astronauts can grow two inches taller in space?",
"Did you know Mars has the largest volcano in the solar system?",
"Did you know black holes can stretch time?",
"Did you know there are more stars than grains of sand on Earth?",
"Did you know sound can’t travel in space?",
"Did you know Earth’s core is as hot as the Sun’s surface?",
"Did you know some atoms in your body are billions of years old?",
"Did you know the universe is still expanding?",
"Did you know the Sun makes up 99.8% of our solar system?",
"Did you know your shadow is different colors depending on the light?",
"Did you know rain can fall sideways in strong winds?",
"Did you know you can boil and freeze water at the same time?",
"Did you know diamonds can form in lightning strikes?",
"Did you know you weigh less at the equator than at the poles?",
"Did you know time feels faster as you age because your brain processes slower?",
"Did you know a rainbow is actually a full circle?",
"Did you know invisible dark matter makes up most of the universe?",
"Did you know astronauts can’t cry normally in space?",
"Did you know the deepest point in the ocean can crush steel?",
"Did you know Wi-Fi was invented by accident while studying black holes?",
"Did you know hot water freezes faster than cold water?",
"Did you know your fingers wrinkle in water to grip better?",
"Did you know the Sun will eventually turn into a giant red star?",
"Did you know space smells like burnt steak?",
"Did you know the ISS travels 17,500 mph around Earth?",
"Did you know a teaspoon of neutron star weighs billions of tons?",
"Did you know every two minutes, humans take more photos than ever existed before 1900?",
"Did you know you are always seeing the past because light takes time to travel?",
"Did you know Earth once had two moons?",
"Did you know GPS wouldn’t work without Einstein’s relativity?",
"Did you know a year on Mercury is only 88 days?",
"Did you know computers can get tired if overheated?",
"Did you know astronauts lose taste in space because fluids shift upward?",
"Did you know a day on Earth is actually 23 hours 56 minutes?",
"Did you know the universe has no center?",
"Did you know some laptops have more bugs than code?",
"Did you know the Milky Way and Andromeda will collide one day?",
"Did you know balloons pop because air pushes out too fast?",
"Did you know microwave ovens were invented by accident?",
"Did you know you can’t sneeze with your eyes open?",
"Did you know paper can be folded more than 7 times with large sheets?",
"Did you know human bodies glow in the dark but eyes can’t see it?",
"Did you know pencils can draw a 35-mile-long line?",
"Did you know the first 3D printer was built in 1983?",
"Did you know 90% of the ocean remains unexplored?",
"Did you know the Earth’s magnetic field flips every few thousand years?",
"Did you know astronauts get taller but their muscles shrink?",
"Did you know the Moon causes most ocean tides?",
"Did you know you can’t tickle yourself?",
"Did you know your brain uses 20% of the oxygen you breathe?",
"Did you know a lava lamp works because oil floats on water?",
"Did you know the northern lights are caused by solar winds?",
"Did you know the universe might be infinite?",
"Did you know light can act as a wave and a particle?",
"Did you know pancakes were once used as medicine?",
"Did you know the first airplane flew slower than a car?",
"Did you know fingerprints are unique even for identical twins?",
"Did you know Earth used to be purple?",
"Did you know sound travels faster in water than air?",
"Did you know magnets work even in outer space?",
"Did you know scientists have created fridges using magnets?",
"Did you know a computer virus once infected NASA?",
"Did you know it rains diamonds on some planets?",
"Did you know your body replaces 98% of its atoms every year?",
"Did you know every planet spins except Mercury and Venus?",
"Did you know most of the universe is invisible?",
"Did you know we are moving through space at 67,000 mph?",
"Did you know dead skin makes up most household dust?",
"Did you know water expands when frozen so ice floats?",
"Did you know the edge of the universe is moving faster than light?",
"Did you know laser stands for Light Amplification by Stimulated Emission of Radiation?",
"Did you know passwords were invented in the 1960s?",
"Did you know some stars explode with more power than a billion Suns?",
"Did you know scientists can stop light completely?",
"Did you know the human brain has more connections than stars in the galaxy?",
"Did you know some clocks lose time because Earth’s rotation slows?",
"Did you know the first computer mouse was made of wood?",
"Did you know static electricity can be hotter than the Sun?",
"Did you know the most powerful number in math is zero?",
"Did you know time would stop in a black hole?",
"Did you know the universe began in less than a trillionth of a second?",
"Clouds can weigh over a million pounds.",
"Bananas are technically berries, but strawberries aren't.",
"A day on Venus is longer than a year on Venus.",
"Honey never spoils, even after thousands of years.",
"The shortest war in history lasted about 38 minutes.",
"It rains diamonds on Jupiter and Saturn.",
"You can't hum while plugging your nose.",
"There are more stars in the universe than grains of sand on Earth.",
"The first computer mouse was made of wood.",
"Water can boil and freeze at the same time.",
"Peanuts aren't actually nuts — they're legumes.",
"Hot water freezes faster than cold water in some conditions.",
"Space is completely silent.",
"Scotland has 421 words for ‘snow’.",
"Your heartbeat syncs with the music you listen to.",
"Some metals like gallium melt in your hand.",
"High-heels were originally worn by men.",
"Humans glow in the dark, but our eyes can't see it.",
"The first oranges weren’t orange — they were green.",
"A jiffy is an actual unit of time — 1/100th of a second.",
"The Eiffel Tower grows taller in the summer due to heat expansion.",
"The hashtag symbol is technically called an octothorpe.",
"Salt was once so valuable it was used as money.",
"The longest English word has 189,819 letters.",
"The entire internet weighs less than a strawberry.",
"Your taste buds replace themselves about every two weeks.",
"The inventor of the frisbee was turned into a frisbee after he died.",
"Most people have at least one dream every night but forget 95% of them.",
"A leap year isn’t every 4 years — exceptions exist.",
"Your brain generates enough electricity to power a lightbulb.",
"Humans are the only animals who blush.",
"Tomatoes were once considered poisonous in Europe.",
"There’s a basketball court on the top floor of the U.S. Supreme Court.",
"Fortune cookies were invented in the U.S., not China.",
"Bubble wrap was originally created as wallpaper.",
"Alaska is the most northern, western, and eastern U.S. state.",
"Oxford University is older than the Aztec Empire.",
"Before erasers, bread was used to remove pencil marks.",
"Chess has more possible games than atoms in the universe.",
"Canada has the longest coastline of any country.",
"Blue eyes are actually a genetic mutation.",
"A group of flamingos is called a ‘flamboyance’.",
"Most laughter isn't because something is funny — it's social.",
"The Great Wall of China isn’t visible from space with the naked eye.",
"New York City was once the capital of the United States.",
"A teaspoon of honey is the lifetime work of 12 bees.",
"Plastic was once more expensive than gold.",
"The moon has moonquakes.",
"Lemons float but limes sink.",
"Humans spend about a year of their life looking for lost items.",
"The U.S. Navy uses Xbox controllers for submarine equipment.",
"Pluto has a heart-shaped glacier.",
"Some languages don’t have a word for the color blue.",
"Your nose gets warmer when you lie.",
"Corn is grown on every continent except Antarctica.",
"Friday the 13th can occur up to three times a year.",
"The first alarm clock could only ring at 4 a.m.",
"Most cities have more trees now than 100 years ago.",
"Apples float because they are 25% air.",
"Wind on Earth is faster than the speed of a car in some storms.",
"Russia is bigger than Pluto.",
"The microwave was invented by accident from radar technology.",
"Diamonds can be made from peanut butter.",
"Super glue was invented by accident.",
"Lightning strikes the Earth 8 million times a day.",
"More people have cell phones than toothbrushes.",
"A broken clock is right twice a day.",
"Mount Everest grows about 4 millimeters every year.",
"Humans share 50% of their DNA with cows — and 60% with bananas.",
"Many major airports have secret runways.",
"The coldest temperature ever recorded on Earth was −128.6°F.",
"People used to drink beer instead of water in medieval times.",
"Bubble tea pearls are made of tapioca from a root.",
"The average person walks around the world 3 times in their lifetime.",
"Every continent except Australia has a location named Rome.",
"Toilet paper was invented in China in the 6th century.",
"Spam emails were named after a Monty Python sketch.",
"Newborn babies don’t cry tears for the first few weeks.",
"Music affects the flavor of food we taste.",
"One light-year is nearly 6 trillion miles.",
"A day on Earth used to be only 18 hours long — millions of years ago.",
"The Statue of Liberty was originally the color of a shiny penny.",
"Humans breathe about 20,000 times per day.",
"Potatoes were the first vegetable grown in space.",
"There's a town named “Dull” that is twinned with “Boring.”",
"Before rubber, basketballs were made of stitched leather.",
"Your fingernails grow faster on your dominant hand.",
"The Pacific Ocean shrinks by about an inch a year.",
"The largest snowflake ever recorded was 15 inches wide.",
"Bamboo can grow nearly a meter in a single day.",
"Cucumbers are 95% water.",
"A rainbow can only be seen in the morning or late afternoon.",
"The average pencil can draw a line 35 miles long.",
"Moon dust smells like gunpowder.",
"Humans are the only species with a chin.",
"Chess was invented over 1,400 years ago.",
"Venus spins backwards compared to most planets.",
"Some people have an extra rib — the cervical rib.",
"The world’s oldest toy is a stick.",
"The dot over the letter “i” is called a tittle.",
"Your phone is dirtier than a toilet seat — typically by 10 times.",
"People used to say “Ahoy!” instead of “Hello!” on the phone.",
];
