// facts.js — pools (animals / space / human). Add more facts here to expand.
const FACT_POOLS = {
  animals: [
    "A group of flamingos is called a flamboyance.",
    "Octopuses have three hearts and blue blood.",
    "Elephants can smell water from twelve miles away.",
    "A snail can sleep for three years straight.",
    "Cows have best friends and get stressed when apart.",
    "Dolphins call each other by name using whistles.",
    "Sloths can hold their breath longer than dolphins.",
    "Penguins propose with pebbles.",
    "Parrots can live longer than humans, up to 100 years.",
    "Butterflies taste with their feet.",
    "Bees can recognize human faces.",
    "Jellyfish have existed longer than dinosaurs.",
    "Koalas have fingerprints like humans.",
    "Sharks are older than trees.",
    "Giraffes have no vocal cords.",
    "Turtles can breathe through their butts.",
    "Frogs can freeze solid and thaw back to life.",
    "Rats laugh when tickled.",
    "Tigers have striped skin, not just striped fur.",
    "Owls can't move their eyes; they turn their heads.",
    "Male seahorses get pregnant.",
    "Crocodiles cannot stick out their tongues.",
    "Cats can’t taste sweetness.",
    "Hippos produce their own natural sunscreen.",
    "Polar bears have black skin.",
    "Some lizards shoot blood from their eyes as defense.",
    "Dolphins sleep with one eye open.",
    "Ants never sleep like humans do.",
    "Honey never spoils.",
    "Camels have three eyelids for sand protection.",
    "Humpback whales create bubble nets to catch fish.",
    "Goats have rectangular pupils for better vision.",
    "A shrimp’s heart is in its head.",
    "Bats often turn left when leaving a cave.",
    "Geckos climb glass with microscopic hairs.",
    "Cheetahs can’t roar — they meow like cats.",
    "Koalas sleep up to 22 hours a day.",
    "Starfish have no brain or blood.",
    "Male penguins incubate eggs for months.",
    "Pigs can learn to play simple video games.",
    "Snakes can sense earthquakes by vibrations.",
    "Goldfish can remember things for months.",
    "Bees have been recorded flying above Everest.",
    "Axolotls regrow limbs and parts of their brain.",
    "Blue whales weigh more than 25 elephants.",
    "Horses can sleep while standing up.",
    "Some octopuses mimic other animals to avoid predators",
    "Rabbits can see almost 360 degrees around them."
  ],

  space: [
    "There are more stars than grains of sand on Earth.",
    "A day on Venus is longer than a year on Venus.",
    "Space is silent — sound can’t travel without air.",
    "Neutron stars can spin hundreds of times per second.",
    "The Moon’s footprints will last millions of years.",
    "There’s a planet with sideways molten glass rain.",
    "Jupiter’s Great Red Spot is larger than Earth.",
    "One million Earths could fit inside the Sun.",
    "Saturn’s average density is low enough to float in water.",
    "There’s a giant cloud of alcohol in space.",
    "Astronauts report space smells like burnt steak and welding.",
    "A spoonful of neutron-star matter would weigh billions of tons.",
    "Astronauts grow taller in microgravity as their spines decompress.",
    "Mars has the tallest volcano in the solar system.",
    "Black holes can stretch and slow down time nearby.",
    "Some planets may have diamond rain.",
    "The universe has no single center — it expands everywhere.",
    "Rogue planets drift without stars.",
    "Pluto has mountains made of water ice.",
    "The Sun is technically white; atmosphere shifts color.",
    "Mercury’s solar day is extremely long — 1,408 Earth hours.",
    "Space exposure can boil fluids at body temperature without a suit.",
    "About 95% of the universe is dark matter/energy.",
    "Time runs slightly differently at different altitudes due to gravity.",
    "Milky Way and Andromeda will collide in billions of years.",
    "There are cosmic microwave background cold spots scientists study.",
    "There could be more planets than stars.",
    "Saturn’s rings slowly fall into the planet over time.",
    "Neptune has storms far larger than Earth’s.",
    "Earth gets hit by roughly 100 tons of space dust daily.",
    "Some galaxies host black holes with jets bigger than galaxies.",
    "NASA prefers tortillas in space to avoid crumbs.",
    "The Moon drifts away about 3.8 cm each year.",
    "Some meteorites predate the Sun itself.",
    "Jupiter’s moons may hold massive subsurface oceans.",
    "You weigh a tiny bit less at the equator than the poles.",
    "Sunlight takes ~8 minutes 20 seconds to reach Earth.",
    "Some galaxies we see are billions of years old.",
    "Heavy elements were formed in ancient stars — stardust.",
    "Lightning occurs on other planets too.",
    "No one truly knows what lies inside a black hole.",
    "Mercury's surface alternates between freezing and frying conditions.",
    "Some planets orbit two or more stars.",
    "The coldest known space cloud is almost absolute zero.",
    "Gravity bends space-time like fabric.",
    "Space expansion can locally exceed speed of light.",
    "There are planets made mostly of deep oceans."
  ],

  human: [
    "You have more bacterial cells than human cells in your body.",
    "Your brain produces enough electricity to power a small light.",
    "Most dreams last only a few seconds of real time.",
    "Goosebumps once helped humans appear larger to threats.",
    "Your skin renews itself about every month.",
    "Humans share many genes with bananas.",
    "The human nose can remember over 50,000 scents.",
    "You blink about 15,000 times per day.",
    "Bone is stronger than steel weight-for-weight.",
    "The brain continues to develop into your mid-20s.",
    "You cannot breathe and swallow at the same time safely.",
    "Stomach lining regenerates every few days to avoid self-digestion.",
    "Blushing increases blood flow in facial tissues.",
    "Music can reduce anxiety and stress measurably.",
    "Your eyes see an upside-down image that the brain flips.",
    "You are slightly taller in the morning than at night.",
    "A lifetime heartbeats total into the billions.",
    "About 70% of your brain is water.",
    "Stress can intensify dreaming patterns.",
    "Your tongue comprises multiple coordinated muscles.",
    "You shed tens of thousands of skin cells every minute.",
    "The heart can continue to beat briefly outside the body.",
    "Some humans can survive without a stomach with medical help.",
    "Laughing triggers immune-boosting physiological reactions.",
    "People emit a tiny amount of visible light, too weak for our eyes.",
    "Ears subtly continue to grow throughout life.",
    "Taste buds refresh every 10–14 days.",
    "Babies are born with about 300 bones that fuse in time.",
    "The brain itself has no pain receptors.",
    "Yawning helps cool the brain and increase alertness.",
    "The liver can regenerate itself in many cases.",
    "Emotions can spread socially — mood contagion.",
    "People are sometimes more honest when tired.",
    "Fear can cause temporary increases in strength (fight-or-flight).",
    "Holding hands can reduce perceived physical pain.",
    "Recalling memories rewrites them slightly each time.",
    "Your heartbeat can sync to music tempo.",
    "Voice patterns are unique like fingerprints.",
    "Many tilt slightly to the right when kissing.",
    "Color red often increases appetite for many people.",
    "Your gut produces small amounts of alcohol naturally.",
    "Walking throughout life can add up to world-circling distances.",
    "First impressions form within seconds of meeting someone.",
    "We spend a big part of waking life staring at screens.",
    "Most dreams fade within minutes of waking.",
    "On the microscopic level your body is always active.",
    "You technically see your nose but the brain filters it out.",
    "False memories can be implanted via suggestion.",
    "Crying helps release stress-related chemical compounds.\n"
  ]
};

// pick unique facts
function pickFacts(poolName='random', count=7){
  const pool = (poolName === 'random') ? [].concat(...Object.values(FACT_POOLS)) : (FACT_POOLS[poolName] || FACT_POOLS['animals']);
  const copy = pool.slice();
  const out = [];
  while(out.length < count && copy.length > 0){
    const i = Math.floor(Math.random() * copy.length);
    out.push(copy.splice(i,1)[0]);
  }
  return out;
}

window.pickFacts = pickFacts;
window.FACT_POOLS = FACT_POOLS;
