const facts = [
"Did you know your nose can remember 50,000 different smells?",
"Did you know your heart beats around 100,000 times per day?",
"Did you know humans grow a new layer of skin every month?",
"Did you know your tongue has between 2,000 and 8,000 taste buds?",
"Did you know laughing can boost your immune system?",
"Did you know your brain is mostly made of fat?",
"Did you know you can’t breathe and swallow at the same time?",
"Did you know your bones are stronger than steel by weight?",
"Did you know you have tiny mites living in your eyelashes?",
"Did you know the average person blinks 15–20 times per minute?",
"Did you know your stomach acid can dissolve razor blades?",
"Did you know humans shed about 1.5 pounds of skin a year?",
"Did you know your feet have a quarter of the bones in your body?",
"Did you know your brain sometimes makes up memories?",
"Did you know the cornea of your eye has no blood vessels?",
"Did you know fingertips have unique skin prints, even on identical twins?",
"Did you know your ears never stop growing?",
"Did you know hiccups can last for years in rare cases?",
"Did you know your heartbeat syncs with the music you listen to?",
"Did you know saliva contains a natural painkiller?",
"Did you know the Sun makes up 99.8% of our solar system’s mass?",
"Did you know a spoonful of a neutron star weighs billions of tons?",
"Did you know there are more stars than grains of sand on Earth?",
"Did you know space is completely silent?",
"Did you know Jupiter has 90% of all known moons in the solar system?",
"Did you know Mars has the tallest volcano in the solar system?",
"Did you know footprints on the Moon can stay for millions of years?",
"Did you know Venus spins in the opposite direction of Earth?",
"Did you know some galaxies are older than the universe should allow?",
"Did you know Saturn could float if put in a giant ocean?",
"Did you know black holes can warp time?",
"Did you know there’s a planet made of diamonds?",
"Did you know the Milky Way is actually moving through space?",
"Did you know space smells like burnt steak according to astronauts?",
"Did you know it rains metal on some exoplanets?",
"Did you know the universe is expanding faster every second?",
"Did you know stars are born inside massive gas clouds?",
"Did you know Pluto has blue skies?",
"Did you know the Sun will become a red giant someday?",
"Did you know astronauts grow taller in space?",
"Did you know octopuses have three hearts?",
"Did you know dolphins have names for each other?",
"Did you know turtles can breathe through their butts?",
"Did you know elephants can recognize themselves in mirrors?",
"Did you know bees can understand zero as a number?",
"Did you know cats can’t taste sweetness?",
"Did you know parrots can live longer than humans?",
"Did you know butterflies taste with their feet?",
"Did you know cows have best friends?",
"Did you know sharks existed before trees?",
"Did you know hippos ooze natural sunscreen?",
"Did you know starfish have no brains?",
"Did you know some frogs can freeze and come back to life?",
"Did you know goats have rectangular pupils?",
"Did you know koalas have fingerprints like humans?",
"Did you know wombat poop is cube-shaped?",
"Did you know seahorses mate for life?",
"Did you know dogs can smell time?",
"Did you know chameleons move their eyes independently?",
"Did you know pigs are smarter than dogs?",
"Did you know water can boil and freeze at the same time?",
"Did you know glass is actually a slow-flowing liquid?",
"Did you know WiFi was invented by accident?",
"Did you know 3D printers can make human organs?",
"Did you know sound travels faster in water than in air?",
"Did you know you can make electricity from lemons?",
"Did you know robots can learn emotions from humans?",
"Did you know magnets work even in outer space?",
"Did you know the first computer bug was an actual bug?",
"Did you know solar power comes from nuclear fusion in the Sun?",
"Did you know lightning is hotter than the Sun?",
"Did you know viruses outnumber all living things on Earth?",
"Did you know some metals explode in water?",
"Did you know your phone is more powerful than old NASA computers?",
"Did you know scientists can slow down light?",
"Did you know diamonds can be made from peanut butter?",
"Did you know lasers are made from light bouncing perfectly?",
"Did you know bananas are slightly radioactive?",
"Did you know snowflakes always have six sides?",
"Did you know atoms are mostly empty space?",
"Did you know we have explored less than 10% of the ocean?",
"Did you know giant squids have eyes the size of dinner plates?",
"Did you know the ocean has underwater lakes and rivers?",
"Did you know there are more historical artifacts underwater than on land?",
"Did you know coral is actually alive?",
"Did you know some fish can walk on land?",
"Did you know the ocean glows at night in some places?",
"Did you know whales have their own dialects?",
"Did you know sea cucumbers can melt their bodies to escape predators?",
"Did you know the deepest ocean point could fit Mount Everest?",
"Did you know your brain rewires itself every time you learn?",
"Did you know your brain can fill in blind spots?",
"Did you know people dream 4–6 times a night?",
"Did you know you can’t dream while snoring?",
"Did you know your brain loves patterns and symmetry?",
"Did you know memories change slightly every time you recall them?",
"Did you know humans are the only animals that procrastinate?",
"Did you know your brain processes images faster than you can blink?",
"Did you know music can change how food tastes?",
"Did you know your brain sometimes wakes you up just before danger?",
"Did you know the Great Wall of China isn’t visible from space?",
"Did you know paper was invented in China over 2,000 years ago?",
"Did you know the first camera took 8 hours to take a photo?",
"Did you know ancient Egyptians used stone pillows?",
"Did you know Vikings used bones to make skate blades?",
"Did you know the first video game was made in 1958?",
"Did you know people once used bread as erasers?",
"Did you know ancient Romans cleaned clothes with pee?",
"Did you know some ancient cities had recycling programs?",
"Did you know the oldest sunglasses were made from walrus ivory?",
"Did you know apples float because they are 25% air?",
"Did you know peanuts aren’t actually nuts?",
"Did you know chocolate used to be used as money?",
"Did you know carrots were originally purple?",
"Did you know strawberries aren’t actually berries?",
"Did you know honey never spoils?",
"Did you know broccoli contains more vitamin C than oranges?",
"Did you know bananas share DNA with humans?",
"Did you know popcorn was invented thousands of years ago?",
"Did you know mushrooms are closer to humans than to plants?",
"Did you know wearing headphones for an hour increases ear bacteria?",
"Did you know your phone carries more bacteria than a toilet seat?",
"Did you know the shortest war lasted only 38 minutes?",
"Did you know a cloud can weigh millions of pounds?",
"Did you know people used to think tomatoes were poisonous?",
"Did you know some hotels skip the 13th floor?",
"Did you know the longest hiccup lasted 68 years?",
"Did you know you forget 90% of your dreams?",
"Did you know ants never sleep?",
"Did you know the first oranges were green?",
"Did you know potatoes were the first vegetables grown in space?",
"Did you know more people die from cows than sharks?",
"Did you know fingerprints can burn off with heat?",
"Did you know Google was almost called BackRub?",
"Did you know tongue prints are unique like fingerprints?",
"Did you know sloths can hold their breath longer than dolphins?",
"Did you know the Eiffel Tower grows in summer from heat expansion?",
"Did you know some perfumes contain whale poop?",
"Did you know you can’t hum while holding your nose?",
"Did you know the moon has moonquakes?",
"Did you know giraffes have the same number of neck bones as humans?",
"Did you know mosquitoes are attracted to people who eat bananas?",
"Did you know birds are dinosaurs’ closest living relatives?",
"Did you know the biggest snowflake ever was 15 inches wide?",
"Did you know Earth’s rotation is slowing over time?",
"Did you know spiders recycle their webs?",
"Did you know rainbows can appear at night?",
"Did you know a group of crows is called a murder?",
"Did you know lightning can strike the same place twice?",
"Did you know jellyfish don’t have brains or hearts?",
"Did you know you’re taller in the morning?",
"Did you know honeybees can recognize human faces?",
"Did you know fire needs gravity to burn in a normal shape?",
"Did you know Antarctica is technically a desert?",
"Did you know bamboo can grow almost a meter per day?",
"Did you know rubber bands last longer when refrigerated?",
"Did you know hot water freezes faster than cold water?",
"Did you know snails can sleep for three years?",
"Did you know flamingos bend their legs at the ankle, not the knee?",
"Did you know ice cubes float because water expands when frozen?",
"Did you know potatoes have more chromosomes than humans?",
"Did you know frogs drink water through their skin?",
"Did you know an eagle’s eyesight is eight times sharper than a human’s?",
"Did you know spiders can survive underwater for hours?",
"Did you know trees can communicate through underground fungi?",
"Did you know ants can lift 50 times their body weight?",
"Did you know newborns don’t have kneecaps?",
"Did you know some birds sleep while flying?",
"Did you know Saturn’s rings are disappearing over time?",
"Did you know the deepest humans have ever gone underground is only 2 miles?",
"Did you know the largest volcano on Earth is underwater?",
"Did you know butterflies remember being caterpillars?",
"Did you know koalas sleep up to 22 hours a day?",
"Did you know the Earth once had two moons?",
"Did you know your blood makes up about 8% of your weight?",
"Did you know some turtles can live over 200 years?",
"Did you know the speed of a sneeze is over 100 mph?",
"Did you know cactuses can live more than 200 years?",
"Did you know camels store fat, not water, in their humps?",
"Did you know diamonds can form inside volcanoes?",
"Did you know raindrops are actually shaped like hamburger buns?",
"Did you know an octopus can regrow lost arms?",
"Did you know onions make you cry to protect themselves?",
"Did you know some fish can glow in the dark?",
"Did you know clouds move faster than cars on highways?",
"Did you know wolves can hear other wolves 10 miles away?",
"Did you know sleep helps clean toxins from your brain?",
"Did you know glass can take a million years to decompose?",
"Did you know baby kangaroos are smaller than gummy bears?",
"Did you know your bones are constantly being replaced?",
"Did you know fish communicate with fart sounds?",
"Did you know polar bears have black skin?",
"Did you know tomatoes are 95% water?",
"Did you know the world’s largest waterfall is underwater?",
"Did you know penguins propose with pebbles?",
"Did you know some lizards can shoot blood from their eyes?",
"Did you know dragonflies can hover like helicopters?",
"Did you know bats are the only mammals that can fly?",
"Did you know honeybees sometimes dance to share food locations?",
  "Did you know humans are the only animals that blush?",
  "Did you know your brain uses about 20% of the calories you eat?",
  "Did you know humans actually glow, but the light is too weak to see?",
  "Did you know your nose can remember 50,000 different scents?",
  "Did you know your jaw muscle is the strongest muscle for its size?",
  "Did you know you lose about 50–100 hairs every day?",
  "Did you know you’re taller in the morning because your spine stretches?",
  "Did you know taste buds only live about 10 days?",
  "Did you know you spend 1 whole year of your life looking for lost things?",
  "Did you know your heart beats over 100,000 times a day?",
  "Did you know you can survive weeks without food but only days without water?",
  "Did you know the acid in your stomach could dissolve metal?",
  "Did you know nails grow faster on your dominant hand?",
  "Did you know your skeleton replaces itself every 10 years?",
  "Did you know babies have 100 more bones than adults?",
  "Did you know goosebumps are a leftover from when humans had fur?",
  "Did you know you blink 15,000 times a day?",
  "Did you know your brain is sometimes more active when asleep?",
  "Did you know your tongue print is unique like a fingerprint?",
  "Did you know sweat doesn’t smell until bacteria mixes with it?",
  "Did you know humans share 60% of their DNA with bananas?",
  "Did you know you produce enough saliva to fill two pools in your life?",
  "Did you know you can’t breathe and swallow at the same time?",
  "Did you know your eye muscles are the fastest in your body?",
  "Did you know laughing boosts your immune system?",
  "Did you know 25% of your bones are in your feet?",
  "Did you know you forget most dreams in 10 minutes?",
  "Did you know humans are the only animals that cry emotionally?",
  "Did you know you will walk around the Earth 5 times in your life?",
  "Did you know your heartbeat syncs with music you listen to?",
  "Did you know a group of flamingos is called a flamboyance?",
  "Did you know octopuses have three hearts?",
  "Did you know cows have best friends?",
  "Did you know sea otters hold hands when sleeping?",
  "Did you know sharks existed before trees?",
  "Did you know snails can sleep for 3 years?",
  "Did you know butterflies taste with their feet?",
  "Did you know elephants recognize themselves in mirrors?",
  "Did you know a group of crows is called a murder?",
  "Did you know rats laugh when tickled?",
  "Did you know some turtles breathe through their butts?",
  "Did you know frogs absorb water through their skin instead of drinking?",
  "Did you know cats can’t taste sweetness?",
  "Did you know giraffes have 20-inch purple tongues?",
  "Did you know a blue whale’s heart is the size of a car?",
  "Did you know dogs’ noses are wet to help smell better?",
  "Did you know bees can remember human faces?",
  "Did you know dolphins give each other names?",
  "Did you know penguins propose with pebbles?",
  "Did you know axolotls can regrow limbs and brain parts?",
  "Did you know crocodiles can’t stick out their tongues?",
  "Did you know koalas sleep up to 22 hours a day?",
  "Did you know cheetahs can hit 60 mph in 3 seconds?",
  "Did you know jellyfish have existed longer than dinosaurs?",
  "Did you know horses can’t vomit?",
  "Did you know owls can rotate their heads 270 degrees?",
  "Did you know sloths poop only once a week?",
  "Did you know male seahorses give birth?",
  "Did you know parrots can live over 60 years?",
  "Did you know kangaroos can’t walk backward?",

  // --- SPACE & UNIVERSE ---
  "Did you know there are more stars than grains of sand on Earth?",
  "Did you know a teaspoon of a neutron star weighs billions of tons?",
  "Did you know space is silent because sound can’t travel in a vacuum?",
  "Did you know Venus spins backwards?",
  "Did you know a day on Venus is longer than a year there?",
  "Did you know there’s a planet made of diamond?",
  "Did you know Jupiter has over 90 moons?",
  "Did you know the sun has 99.8% of our solar system’s mass?",
  "Did you know driving straight up would reach space in one hour?",
  "Did you know some galaxies move faster than light?",
  "Did you know a spacesuit costs more than $12 million?",
  "Did you know black holes slow down time around them?",
  "Did you know Saturn could float in water?",
  "Did you know there’s a space cloud smelling like rum?",
  "Did you know Moon footprints stay for millions of years?",
  "Did you know astronauts grow taller in space?",
  "Did you know the Milky Way is eating other galaxies?",
  "Did you know Mars has the biggest volcano in the solar system?",
  "Did you know a day on Mars is only 40 minutes longer than Earth?",
  "Did you know stars don’t twinkle in space?",
  "Did you know tears don’t fall in space?",
  "Did you know some planets rain glass sideways?",
  "Did you know sunlight takes 8 minutes to reach Earth?",
  "Did you know there are more planets than stars?",
  "Did you know we only see 5% of the universe?",
  "Did you know astronauts have special tubes to pee while in suits?",
  "Did you know galaxies collide and merge all the time?",
  "Did you know the first image of a black hole was taken in 2019?",
  "Did you know the universe expands every second?",
  "Did you know the sun will grow so big it will swallow Earth one day?",

  // --- TECHNOLOGY ---
  "Did you know the first computer mouse was wooden?",
  "Did you know your phone is stronger than the computers used for the Moon landing?",
  "Did you know there are more phones than humans?",
  "Did you know Google gets over 100,000 searches per second?",
  "Did you know email is older than the World Wide Web?",
  "Did you know the save icon is a picture of a floppy disk?",
  "Did you know the first 1TB drive came in 2007?",
  "Did you know over 3 billion people play video games?",
  "Did you know the creator of GIF says it’s pronounced “JIF”?",
  "Did you know the first alarm clock only rang at 4 AM?",
  "Did you know Bluetooth is named after a Viking king?",
  "Did you know 90% of the world’s money is digital?",
  "Did you know the first website ever is still online?",
  "Did you know your phone knows if you run, walk, or lie down?",
  "Did you know the first picture took 8 hours to capture?",
  "Did you know drones deliver medicine to remote places?",
  "Did you know the first text message ever was “Merry Christmas”?",
  "Did you know Wi-Fi doesn’t stand for anything?",
  "Did you know Nintendo was made before airplanes?",
  "Did you know astronauts use tablets instead of paper in space?",
  "Did you know there’s a supercomputer as small as a rice grain?",
  "Did you know QR codes were invented for cars?",
  "Did you know typing wrong passwords too much can lock you out for years?",
  "Did you know some cars update software like phones?",
  "Did you know robots can learn emotions from faces?",
  "Did you know you check your phone over 100 times a day?",
  "Did you know 3D printers can build houses?",
  "Did you know AI can write music better than humans sometimes?",
  "Did you know VR can make your brain think heights are real?",
  "Did you know self-driving cars scan the world 10 times a second?",
  "Did you know humans can live without food longer than without sleep?",
  "Did you know your brain can read jumbled words as long as the first and last letters are correct?",
  "Did you know you can’t hum while holding your nose?",
  "Did you know the average person has 70,000 thoughts a day?",
  "Did you know most people can't swallow twice in a row on purpose?",
  "Did you know your brain sometimes creates fake memories?",
  "Did you know yawning cools down your brain?",
  "Did you know your ears never stop growing?",
  "Did you know your brain deletes memories while you're dreaming?",
  "Did you know your heartbeat speeds up when you look at someone you love?",
  "Did you know most laughter isn’t because something is funny?",
  "Did you know your blood is blue until exposed to oxygen? (It’s actually dark red!)",
  "Did you know most people breathe only through one nostril at a time?",
  "Did you know your belly button is home to thousands of bacteria?",
  "Did you know your eyes see everything upside down? Your brain flips it.",
  "Did you know when you blush, your stomach blushes too?",
  "Did you know humans are the best long-distance runners on Earth?",
  "Did you know kids laugh around 300 times a day and adults only 20?",
  "Did you know teeth are the only body part that can’t repair themselves?",
  "Did you know your brain can store about 2.5 million gigabytes of memories?",
  "Did you know being cold can make you feel lonely?",
  "Did you know people tend to walk faster when they listen to music?",
  "Did you know you can’t tickle yourself because your brain predicts it?",
  "Did you know your fingers wrinkle in water to grip better?",
  "Did you know your dominant eye aims when you point at things?",
  "Did you know every human started as a single cell?",
  "Did you know your lips are 100 times more sensitive than fingertips?",
  "Did you know humans shed 8 pounds of skin every year?",
  "Did you know humans and zebras have the same number of neck bones?",
  "Did you know the brain named itself?",
  "Did you know most people dream in pictures, not words?",
  "Did you know your brain knows when someone is staring at you?",
  "Did you know holding a warm drink makes you think others are nicer?",
  "Did you know you’re more creative in the shower?",
  "Did you know people are naturally scared of loud, sudden sounds?",
  "Did you know you're more likely to trust someone who mirrors your actions?",
  "Did you know sneezes can travel 100 mph?",
  "Did you know your hair grows faster in the summer?",
  "Did you know babies don't cry tears until they are about 6 weeks old?",
  "Did you know stress can make your hair turn white?",
  "Did you know your bones are stronger than steel?",
  "Did you know smiling can trick your brain into feeling happy?",
  "Did you know chewing gum boosts memory?",
  "Did you know you can't breathe through your nose while talking?",
  "Did you know your brain stops you from remembering pain exactly?",
  "Did you know humans can distinguish more than a trillion smells?",
  "Did you know your skin is your biggest organ?",
  "Did you know people feel safer in bright rooms than dark ones?",
  "Did you know your brain reacts more to negative news than positive?",
  "Did you know humans glow brighter in the afternoon?",
  "Did you know that when you blush, your veins widen?",
  "Did you know some people have no fingerprints?",
  "Did you know you clean your ears too much? Earwax protects you.",
  "Did you know your heart can literally break from sadness?",
  "Did you know babies have 10,000 taste buds?",
  "Did you know your brain looks like Jell-O?",
  "Did you know your nose works better in the morning?",
  "Did you know humans are the only mammals that can talk?",
  "Did you know you breathe differently when thinking hard?",
  "Did you know your eyebrows keep sweat out of your eyes?",
  "Did you know pressure can change the taste of food?",
  "Did you know stomach growling is your intestines cleaning?",
  "Did you know your pupils get bigger when you see someone attractive?",
  "Did you know the brain feels no pain?",
  "Did you know you forget 90% of your dreams?",
  "Did you know memory pops up better when you smell something familiar?",
  "Did you know humans are born with more neck strength than expected (to help hold the head)?",
  "Did you know yawning is contagious even in dogs?",
  "Did you know your skin renews every 30 days?",
  "Did you know hiccups can last for years?",
  "Did you know your tongue never gets tired?",
  "Did you know intense focus makes you breathe slower?",
  "Did you know you can smell rain?",
  "Did you know your brain always tries to protect your feelings?",
  "Did you know your blood vessels could circle Earth twice?",
  "Did you know blinking helps your brain stay awake?",
  "Did you know your fingerprints help you grip things?",
  "Did you know the brain interprets rejection as physical pain?",
  "Did you know being around happy people makes you happier?",
  "Did you know shivering burns calories?",
  "Did you know fear can freeze your body from moving?",
  "Did you know your heartbeat changes with your breathing?",
  "Did you know pessimists live shorter lives?",
  "Did you know your brain can't recognize letters with no shapes?",
  "Did you know humans crave stories more than facts?",
  "Did you know some people dream only in black and white?",
  "Did you know most people spend 10 years of life on screens?",
  "Did you know silence helps your brain grow new cells?",
  "Did you know hearing your name grabs your attention instantly?",
  "Did you know stretching after waking up gives more energy than coffee?",
  "Did you know your brain believes everything you tell it?",
  "Did you know touching something warm makes you kinder?",
  "Did you know your eyes see 7 million colors?",
  "Did you know goosebumps tried to keep fur from falling off?",
  "Did you know your nose gets stuffy more on one side?",
  "Did you know a bad memory helps creativity?",
  "Did you know your joints can actually sense weather changes?",
  "Did you know the smell of chocolate makes people relax?",
  "Did you know anxiety tricks you into thinking?",
  "Did you know men and women blink at different speeds?",
  "Did you know humans get goosebumps during powerful music?",
  "Did you know people feel time move slower when scared?",
  "Did you know pain tolerance increases when you’re happy?",
  "Did you know your brain sometimes creates feelings for no reason?",
  "Did you know loud music makes you want to spend more money?",
  "Did you know your body has tiny particles left from stars?",
  "Did you know kindness is contagious?",
  "Did you know biting nails can be a stress habit?",
  "Did you know you trust people who talk like you?",
  "Did you know your tears have different chemicals depending on emotion?",
  "Did you know your brain daydreams on purpose to solve problems?",
  "Did you know sugar can be more addictive than cocaine?",
  "Did you know humans are 99.9% genetically the same?",
  "Did you know your spine protects your brain when you fall?",
  "Did you know your heartbeat can sync with someone else's?",
  "Did you know fear makes your eyes widen to see danger better?",
  "Did you know a happier brain learns faster?",
  "Did you know most people talk to themselves in their head?",
  "Did you know writing down worries reduces stress?",
  "Did you know you sleep better in a clean room?",
  "Did you know deep breaths calm the nervous system?",
  "Did you know self-confidence can trick others into believing you?",
  "Did you know focusing on breathing improves memory?",
  "Did you know the brain rewires after every new experience?",
  "Did you know people who use emojis seem more likable?",
  "Did you know smelling lavender helps with anxiety?",
  "Did you know optimism boosts your immune system?",
  "Did you know small wins give big motivation?",
  "Did you know humans learn best by teaching others?",
  "Did you know hearing someone yawn makes you yawn?",
  "Did you know people blink slower when lying?",
  "Did you know hugging for 20 seconds boosts happiness chemicals?",
  "Did you know adrenaline makes time feel slower?",
  "Did you know listening to music you love boosts performance?",
  "Did you know fear can make you stronger?",
  "Did you know missing someone can make your chest physically hurt?",
  "Did you know the brain hates unfinished tasks?",
  "Did you know excitement and fear feel almost the same?",
  "Did you know the brain rewards you for being curious?",
  "Did you know you remember beginnings and endings the most?",
  "Did you know calming colors lower heart rate?",
  "Did you know urgency makes people act 10 times faster?",
  "Did you know laughing with someone builds strong trust?",
  "Did you know people mirror accents without trying?",
  "Did you know imagining exercise can build muscle?",
  "Did you know humans are more creative when tired?",
  "Did you know good posture improves confidence?",
  "Did you know smiling makes others smile automatically?",
  "Did you know your brain prefers negative news because it seems safer?",
  "Did you know most people like the smell of gasoline?",
  "Did you know loud chewing makes some people angry?",
  "Did you know your brain rewrites memories each time you remember them?",
  "Did you know hearing your favorite song can make you cry?",
  "Did you know even fake laughter boosts happiness?",
  "Did you know eye contact shows confidence and trust?",
  "Did you know dehydration makes thinking harder?",
  "Did you know panic makes breathing shallow and fast?",
  "Did you know confidence is more attractive than looks?",
  "Did you know a compliment can boost someone’s mood for weeks?",
  "Did you know friendships increase life expectancy?",
  "Did you know facing fears makes the brain stronger?",
  "Did you know loving someone changes your brain chemistry?",
  "Did you know your brain grows when you learn something new?",
  "Did you know curiosity cures boredom instantly?",
  "Did you know sad music can make you feel better?",
  "Did you know you unconsciously copy the people you admire?",
  "Did you know negative thinking makes your brain weaker?",
  "Did you know some memories are stored forever?",
  "Did you know daydreaming is a sign of intelligence?",
  "Did you know excitement makes your heart beat faster than fear?",
  "Did you know people become different versions of themselves around different groups?",
"Did you know honey never spoils?",
"Did you know octopuses have three hearts?",
"Did you know bananas are actually berries?",
"Did you know a shrimp’s heart is in its head?",
"Did you know the Eiffel Tower grows in the summer?",
"Did you know some turtles can breathe through their butts?",
"Did you know your tongue is the strongest muscle by size?",
"Did you know cows have best friends?",
"Did you know dolphins give each other names?",
"Did you know wombat poop is cube-shaped?",
"Did you know sharks existed before trees?",
"Did you know a snail can sleep for 3 years?",
"Did you know butterflies taste with their feet?",
"Did you know peanuts aren’t nuts?",
"Did you know crows remember faces?",
"Did you know the moon has moonquakes?",
"Did you know sea otters hold hands while they sleep?",
"Did you know there are more stars in the universe than grains of sand on Earth?",
"Did you know strawberries aren’t berries?",
"Did you know ants never sleep?",
"Did you know the strongest bone in your body is the jawbone?",
"Did you know a day on Venus is longer than a year on Venus?",
"Did you know cats can’t taste sweetness?",
"Did you know your brain named itself?",
"Did you know jellyfish don’t have brains?",
"Did you know humans share 60% of our DNA with bananas?",
"Did you know sloths can hold their breath longer than dolphins?",
"Did you know apples float because they’re 25% air?",
"Did you know bees can recognize human faces?",
"Did you know cheetahs can’t roar?",
"Did you know the shortest war lasted only 38 minutes?",
"Did you know hot water freezes faster than cold water?",
"Did you know a cloud can weigh more than a million pounds?",
"Did you know frogs can freeze solid and survive?",
"Did you know goldfish can live 40 years?",
"Did you know mosquitoes are the deadliest animals on Earth?",
"Did you know space smells like burnt steak?",
"Did you know fish can drown?",
"Did you know turtles can feel through their shells?",
"Did you know an eagle can see a rabbit 3 miles away?",
"Did you know whales can live over 200 years?",
"Did you know some metals explode when touching water?",
"Did you know dragonflies can fly backward?",
"Did you know the human nose can detect a trillion smells?",
"Did you know plants can talk to each other chemically?",
"Did you know the heart beats over 2 billion times in a lifetime?",
"Did you know lightning is hotter than the sun?",
"Did you know the first oranges weren’t orange?",
"Did you know fire can burn in space?",
"Did you know the largest living structure is the Great Barrier Reef?",
  "Did you know spiders can dream?",
  "Did you know a blue whale’s veins are so large a human could swim through them?",
  "Did you know bananas are naturally radioactive?",
  "Did you know squirrels can’t burp or vomit?",
  "Did you know the dot over the letter ‘i’ is called a tittle?",
  "Did you know sharks can go into a trance if flipped upside down?",
  "Did you know Venus spins backwards compared to other planets?",
  "Did you know lobsters pee out of their faces?",
  "Did you know bees can recognize human faces?",
  "Did you know some turtles can breathe through their backsides?",
  "Did you know the moon has moonquakes?",
  "Did you know goats have accents depending on where they grow up?",
  "Did you know a group of ferrets is called a business?",
  "Did you know tomatoes were once considered poisonous?",
  "Did you know astronauts can’t cry in space like on Earth?",
  "Did you know your phone has more computing power than the first moon landing?",
  "Did you know cats have fewer toes on their back paws?",
  "Did you know spiders recycle their webs by eating them?",
  "Did you know clouds fly higher in the summer?",
  "Did you know the human nose can detect fear?",
  "Did you know dragonflies can fly backwards?",
  "Did you know birds don’t urinate?",
  "Did you know sea cucumbers can shoot their organs as a defense?",
  "Did you know camels have three eyelids?",
  "Did you know octopuses can taste with their arms?",
  "Did you know ants take naps throughout the day instead of sleeping at night?",
  "Did you know wolves and ravens hunt together for fun?",
  "Did you know a baby puffin is called a puffling?",
  "Did you know horses can grow mustaches?",
  "Did you know oysters can change gender?",
  "Did you know frogs can throw up their entire stomach?",
  "Did you know butterflies can’t fly if they’re too cold?",
  "Did you know crocodiles swallow rocks for weight control?",
  "Did you know bees can vote?",
  "Did you know a hummingbird’s heart beats over 1,200 times per minute?",
  "Did you know elephants can die of heartbreak?",
  "Did you know mosquitoes are attracted to stinky feet?",
  "Did you know shrimp can see colors humans can’t even imagine?",
  "Did you know zebras are born with brown stripes that turn black?",
  "Did you know the sun makes up 99.86% of our solar system’s mass?",
  "Did you know there’s a planet where glass rains sideways?",
  "Did you know astronauts’ suits cost more than a Lamborghini?",
  "Did you know babies don’t have kneecaps?",
  "Did you know our teeth are as strong as shark teeth?",
  "Did you know people are taller in space?",
  "Did you know you can see your own nose — your brain just ignores it?",
  "Did you know giraffes have purple tongues to avoid sunburn?",
  "Did you know rats laugh when tickled?",
  "Did you know sunflowers move to follow the sun?",
  "Did you know a sneeze can launch droplets 30 feet?",
  "Did you know you’re more likely to win the lottery than be bitten by a bat?",
  "Did you know dolphins have bellybuttons?",
  "Did you know cats meow only to communicate with humans?",
  "Did you know pigs have best friends?",
  "Did you know Americans eat 350 slices of pizza every second?",
  "Did you know “hippopotomonstrosesquipedaliophobia” is the fear of long words?",
  "Did you know most dust in your home is dead skin?",
  "Did you know the human eye can distinguish around 10 million colors?",
  "Did you know tigers have striped skin not just fur?",
  "Did you know the first oranges were green?",
  "Did you know ketchup was sold as medicine in the 1830s?",
  "Did you know ice cream used to be called ‘cream ice’?",
  "Did you know cows have 300-degree vision?",
  "Did you know if you could drive straight up, you’d reach space in an hour?",
  "Did you know onions were once used as currency in Egypt?",
  "Did you know your brain can store the internet’s entire data and more?",
  "Did you know Saturn has storms larger than Earth?",
  "Did you know goldfish can recognize their owners?",
  "Did you know octopuses have blue blood?",
  "Did you know kangaroos can’t move their legs independently?",
  "Did you know geckos can stick to walls using tiny hairs?",
  "Did you know blue eyes are actually colorless?",
  "Did you know temperature affects your handwriting?",
  "Did you know turtles can live longer than humans?",
  "Did you know flamingos bend their legs at the ankle not the knee?",
  "Did you know mice sing songs to impress mates?",
  "Did you know fingerprints can disappear if burned enough?",
  "Did you know cold water weighs more than hot water?",
  "Did you know the universe has more galaxies than stars in our galaxy?",
  "Did you know peanuts explode in space?",
  "Did you know ducks’ quacks do not echo?",
  "Did you know sound travels faster in water than air?",
  "Did you know rainbows are actually full circles?",
  "Did you know turtles can experience love?",
  "Did you know horses can’t breathe through their mouths?",
  "Did you know parrots can dance to music?",
  "Did you know fire whirls exist like tornadoes made of flames?",
  "Did you know cows milk more when music plays?",
  "Did you know the longest hiccup attack lasted 68 years?",
  "Did you know snails can regrow broken shells?",
  "Did you know snakes can have two heads?",
  "Did you know wasps remember human faces?",
  "Did you know pigeons can do math?",
  "Did you know ostriches can outrun horses?",
  "Did you know spiders have hydraulic legs powered by fluid?",
  "Did you know hot water sometimes freezes faster than cold?",
  "Did you know you breathe in 20,000 times a day?",
  "Did you know koalas have fingerprints like humans?",
  "Did you know cats purr to heal themselves?",
  "Did you know dolphins sleep with half their brain awake?",
  "Did you know a giraffe’s kick can kill a lion?",
  "Did you know frogs absorb water through their skin instead of drinking?",
  "Did you know dragonflies can hover like helicopters?",
  "Did you know seahorses are the only animals where dads give birth?",
  "Did you know dogs can smell your feelings?",
  "Did you know hummingbirds can fly upside down?",
  "Did you know scorpions glow under UV light?",
  "Did you know jellyfish don’t die of old age?",
  "Did you know the first camera took 8 hours to capture a photo?",
  "Did you know sharks don’t get cancer easily?",
  "Did you know baby giraffes fall 6 feet at birth?",
  "Did you know ants have two stomachs?",
  "Did you know rhinos communicate by poop piles?",
  "Did you know sloths can hold their breath for 40 minutes?",
  "Did you know elephants have 40,000 muscles in their trunk?",
  "Did you know spiders can float across oceans using silk like a kite?",
  "Did you know fish can drown if they don’t get enough oxygen?",
  "Did you know woodpeckers wrap their tongues around their brains for protection?",
  "Did you know Pluto has mountains made of ice?",
  "Did you know lightning strikes Earth 100 times per second?",
  "Did you know snails can have up to 24,000 teeth?",
  "Did you know the Milky Way smells like raspberries?",
  "Did you know octopuses throw objects when angry?",
  "Did you know tapping your head can help freeze brain pain?",
  "Did you know ants take slaves from other colonies?",
  "Did you know camels can close their nostrils?",
  "Did you know clouds can weigh over a billion pounds?",
  "Did you know a cat once was mayor of a town for 20 years?",
  "Did you know the moon has its own timezone?",
  "Did you know the Earth used to be purple?",
  "Did you know your brain can’t create new faces in dreams?",
  "Did you know spiders use electricity to fly?",
  "Did you know Venus has acid rain?",
  "Did you know a cockroach can live a week without its head?",
  "Did you know cows brush against each other like humans hugging?",
  "Did you know mushrooms can communicate through a network like the internet?",
  "Did you know flamingos stand on one leg to conserve heat?",
  "Did you know dolphins can see with sound?",
  "Did you know chocolate contains a chemical that dogs can overdose on?",
  "Did you know rabbits can die from fright?",
  "Did you know sneezes reset your brain?",
  "Did you know astronauts get taller in space?",
  "Did you know snakes can sense warmth like night vision?",
  "Did you know your bones are constantly dissolving and rebuilding?",
  "Did you know the Great Wall of China isn’t visible from space?",
  "Did you know snow isn’t white — it’s clear?",
  "Did you know bees can detect explosives?",
  "Did you know oranges used to be a luxury privilege?",
  "Did you know 8% of the world has blue eyes?",
  "Did you know whales can die by drowning?",
  "Did you know worms can regrow into two worms?",
  "Did you know stars can explode louder than 10 billion nukes?",
  "Did you know the Sun is actually white in space?",
  "Did you know the Earth hums constantly?",
  "Did you know you can hear a blue whale heartbeat from 2 miles away?",
  "Did you know honeybees can fly at 20 mph?",
  "Did you know fish can learn tricks like dogs?",
  "Did you know tigers have antiseptic saliva?",
  "Did you know a bee’s wings beat 11,400 times per minute?",
  "Did you know humans are the only animals that cook food?",
  "Did you know manta rays have the biggest brains in fish?",
  "Did you know sloths can take a month to digest a meal?",
  "Did you know every planet can fit between Earth and the moon with room to spare?",
  "Did you know Jupiter makes its own heat?",
  "Did you know octopuses can solve puzzles?",
  "Did you know snow can fall at 9 feet per second?",
  "Did you know dolphins use tools to hunt?",
  "Did you know goats can solve simple puzzles?",
  "Did you know sharks can detect a drop of blood in 25 gallons of water?",
  "Did you know polar bears have black skin?",
  "Did you know flamingos can only eat with their heads upside down?",
  "Did you know crocodiles can digest bones?",
  "Did you know starfish have no blood?",
  "Did you know you’re more bacteria than human cells?",
  "Did you know elephants mourn their dead?",
  "Did you know butterflies smell through their antennae?",
  "Did you know hippos can run faster than humans?",
  "Did you know some fish glow in the dark?",
  "Did you know spiders can regenerate lost limbs?",
  "Did you know hedgehogs can swim?",
  "Did you know moths remember things from when they were caterpillars?",
  "Did you know the deepest part of the ocean is deeper than Mount Everest is tall?",
  "Did you know the average cloud weighs more than 1 million pounds?",
  "Did you know bananas are berries but strawberries aren’t?",
  "Did you know octopuses have three hearts?",
  "Did you know honey never spoils and can last thousands of years?",
  "Did you know your fingernails grow faster in summer?",
  "Did you know sloths only poop once a week?",
  "Did you know cows have best friends?",
  "Did you know butterflies taste with their feet?",
  "Did you know a sneeze can travel over 100 mph?",
  "Did you know sharks existed before trees?",
  "Did you know jellyfish are 95% water?",
  "Did you know turtles breathe through their butts?",
  "Did you know hot water freezes faster than cold water?",
  "Did you know the Eiffel Tower grows in the summer due to heat?",
  "Did you know hippos sweat red?",
  "Did you know the smell of rain is called petrichor?",
  "Did you know peanuts aren’t nuts?",
  "Did you know the moon has moonquakes?",
  "Did you know whales have belly buttons?",
  "Did you know a day on Venus is longer than a year on Venus?",
  "Did you know otters hold hands while they sleep?",
  "Did you know kangaroos can’t walk backwards?",
  "Did you know the longest recorded sneeze lasted 978 days?",
  "Did you know bees can recognize human faces?",
  "Did you know wombat poop is cube-shaped?",
  "Did you know some fish can walk on land?",
  "Did you know your taste buds have a lifespan of 10–14 days?",
  "Did you know goldfish have a longer memory than humans think?",
  "Did you know flamingos are only pink because of their diet?",
  "Did you know a crocodile can’t stick its tongue out?",
  "Did you know space is completely silent?",
  "Did you know dolphins call each other by name?",
  "Did you know spiders have blue blood?",
  "Did you know the largest living structure is the Great Barrier Reef?",
  "Did you know honeybees flap their wings 230 times per second?",
  "Did you know water makes different sounds depending on temperature?",
  "Did you know elephants can ‘hear’ with their feet?",
  "Did you know snails can sleep up to 3 years?",
  "Did you know cats can’t taste sweetness?",
  "Did you know penguins give their mates a pebble as a gift?",
  "Did you know a group of crows is called a murder?",
  "Did you know your bones are stronger than concrete?",
  "Did you know the universe has more stars than grains of sand on Earth?",
  "Did you know giraffes only sleep about 30 minutes a day?",
  "Did you know plants can communicate with each other?",
  "Did you know blueberries are one of the only naturally blue foods?",
  "Did you know the smallest bone in the body is in your ear?",
  "Did you know a single strand of hair can hold up to 100 grams?",
  "Did you know spiders can fly using electricity in the air?",
  "Did you know there are more fake flamingos in the world than real ones?",
  "Did you know camels have three eyelids?",
  "Did you know lightning is hotter than the surface of the sun?",
  "Did you know frozen lobsters can come back to life when thawed?",
  "Did you know avocados were once banned in France?",
  "Did you know dolphins sleep with one eye open?",
  "Did you know the human heart can squirt blood 30 feet?",
  "Did you know ants don’t have lungs?",
  "Did you know sharks can live for 500 years?",
  "Did you know mushrooms are closer to humans than plants genetically?",
  "Did you know astronauts grow taller in space?",
  "Did you know mosquitoes are the deadliest animal?",
  "Did you know a blue whale’s heart weighs as much as a car?",
  "Did you know cats only meow to communicate with humans?",
  "Did you know the Earth isn’t perfectly round?",
  "Did you know parrots can live over 80 years?",
  "Did you know spiders recycle their webs by eating them?",
  "Did you know the smell of cut grass is a plant distress signal?",
  "Did you know you can’t hum while pinching your nose?",
  "Did you know sharks are immune to cancer myths aren’t fully true?",
  "Did you know flamingos bend their legs at the ankle, not the knee?",
  "Did you know brain freeze happens when blood vessels rapidly widen?",
  "Did you know parrots can dance to music?",
  "Did you know frogs drink water through their skin?",
  "Did you know your belly button is home to thousands of bacteria?",
  "Did you know ocean waves sometimes travel backward?",
  "Did you know jellyfish don’t have brains?",
  "Did you know taste buds can detect over 100,000 flavors?",
  "Did you know goats have rectangular pupils?",
  "Did you know some turtles can breathe through their skin?",
  "Did you know rainbows actually form full circles?",
  "Did you know owls can rotate their heads 270 degrees?",
  "Did you know spiders can regrow legs?",
  "Did you know corn always has an even number of rows?",
  "Did you know cats have whiskers on their legs?",
  "Did you know sea otters have pockets in their fur?",
  "Did you know sloths can hold their breath longer than dolphins?",
  "Did you know carrots were originally purple?",
  "Did you know octopuses can change personality?",
  "Did you know the human eye can detect 7 million colors?",
  "Did you know crocodiles can climb trees?",
  "Did you know sharks sleep with their eyes open?",
  "Did you know some metals explode when they touch water?",
  "Did you know the Milky Way smells like raspberries and rum?",
  "Did you know spiders can dream?",
  "Did you know sweat itself doesn’t smell?",
  "Did you know your tongue is made of 8 muscles?",
  "Did you know polar bears have black skin?",
  "Did you know the Earth has more than one moon? (small quasi-moons!)",
  "Did you know cats have a ‘purr button’ in their spine?",
  "Did you know foxes can use Earth’s magnetic field to hunt?",
  "Did you know butterflies can remember being caterpillars?",
  "Did you know lightning can strike the same place twice?",
  "Did you know bees sometimes sting other bees?",
  "Did you know hummingbirds are the only birds that can fly backward?",
  "Did you know octopuses can taste everything they touch?",
  "Did you know astronauts can’t cry properly in space?",
  "Did you know pufferfish build underwater art to attract mates?",
  "Did you know human bones regenerate completely every 10 years?",
  "Did you know parrots can learn over 1,000 words?",
  "Did you know some worms can regrow their entire bodies from one cell?",
  "Did you know the human nose can detect 1 trillion scents?",
  "Did you know cows can walk upstairs but not downstairs?",
  "Did you know dragonflies can fly up to 60 mph?",
  "Did you know birds don’t urinate?",
  "Did you know Venus rotates in the opposite direction of Earth?",
  "Did you know some ants farm aphids like cows?",
  "Did you know sea stars can regenerate arms?",
  "Did you know salt used to be more expensive than gold?",
  "Did you know humans have jumped higher on the moon than Earth?",
  "Did you know spiders can survive underwater for hours?",
  "Did you know zebras are black with white stripes?",
  "Did you know Saturn could float in water?",
  "Did you know carrots help you see in the dark is a myth?",
  "Did you know one day on Mercury equals 59 days on Earth?",
  "Did you know glowworms aren’t worms?",
  "Did you know humans share 60% of DNA with bananas?",
  "Did you know turtles can feel through their shells?",
  "Did you know ice cream was once considered medicine?",
  "Did you know wild dolphins teach each other tricks?",
  "Did you know Komodo dragons have poisonous saliva?",
  "Did you know the loudest animal is a tiny shrimp?",
  "Did you know you can fit 1.3 million Earths inside the sun?",
  "Did you know bubbles always pop the same shape?",
  "Did you know fireflies aren’t flies?",
  "Did you know Earth used to be purple instead of blue?",
  "Did you know sharks can see in the dark?",
  "Did you know every snowflake has six sides?",
  "Did you know bees can fly higher than Mount Everest?",
  "Did you know ants never sleep?",
  "Did you know bananas glow blue under black light?",
  "Did you know spiders don’t have muscles in their legs?",
  "Did you know a snail’s teeth are stronger than steel?",
  "Did you know snakes smell with their tongues?",
  "Did you know grasshoppers have ears on their bellies?",
  "Did you know ravens can solve complicated puzzles?",
  "Did you know dolphins can stay awake for 15 days?",
  "Did you know some frogs freeze but come back to life?",
  "Did you know crickets have different chirps by temperature?",
  "Did you know lions sleep 20 hours a day?",
  "Did you know sharks don’t have bones?",
  "Did you know aardvarks are the only ones in their animal family?",
  "Did you know worms have five hearts?",
  "Did you know butterflies can see ultraviolet light?",
  "Did you know dogs can learn 250 words?",
  "Did you know pigs can use mirrors?",
  "Did you know peanuts are used to make dynamite?",
  "Did you know tiny tardigrades can survive outer space?",
  "Did you know even penguins have knees?"
];
